using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DeconTools.Backend.Parameters;
using GetPeaks_DLL.Objects;
using DeconTools.Backend.Core;

namespace GetPeaks_DLL.Go_Decon_Modules
{
    public class GoTransformParameters
    {
        public string DeconToolsParameterFile { get; set; }

        public bool LoadParametersFromFile {get;set;}

        public HornTransformParameters Parameters { get; set; }

        public DeconToolsV2.HornTransform.clsHornTransformParameters DeconThrashParameters { get; set; }

        public GoTransformParameters(string deconToolsParameterFile, bool LoadFromFile)
        {
            int numScansToSumOver = 2;//this is smelly
            LoadParametersFromFile = LoadFromFile;//use built in parameters
            DeconToolsParameterFile = deconToolsParameterFile;
            Parameters = new HornTransformParameters();
            
            loadDeconEngineHornParameters(numScansToSumOver);
        }

        public GoTransformParameters()
        {
            int numScansToSumOver = 2;//this is smelly
            LoadParametersFromFile = false;//use built in parameters
            Parameters = new HornTransformParameters();
            loadDeconEngineHornParameters(numScansToSumOver);
        }

        public DeconToolsV2.HornTransform.clsHornTransformParameters loadDeconEngineHornParameters(int numScansToSumOver)
        {
            //bool loadParametersFromFile = true;

            if (LoadParametersFromFile)
            {
                string parameterFile = DeconToolsParameterFile;
                var parameters = new OldDecon2LSParameters();
                parameters.Load(parameterFile);
                

                DeconThrashParameters = new DeconToolsV2.HornTransform.clsHornTransformParameters();
                DeconThrashParameters = parameters.HornTransformParameters;
            }
            else
            {

                DeconThrashParameters = new DeconToolsV2.HornTransform.clsHornTransformParameters();
                DeconThrashParameters.AbsolutePeptideIntensity = Parameters.AbsolutePeptideIntensity;
                DeconThrashParameters.AveragineFormula = Parameters.AveragineFormula; //SK
                DeconThrashParameters.CCMass = Parameters.CCMass;
                DeconThrashParameters.CheckAllPatternsAgainstCharge1 = Parameters.CheckAllPatternsAgainstCharge1;
                DeconThrashParameters.CompleteFit = Parameters.CompleteFit;
                DeconThrashParameters.DeleteIntensityThreshold = Parameters.DeleteIntensityThreshold;
                DeconThrashParameters.IsActualMonoMZUsed = Parameters.IsActualMonoMZUsed;
                DeconThrashParameters.IsotopeFitType = Parameters.IsotopeFitType;
                DeconThrashParameters.LeftFitStringencyFactor = Parameters.LeftFitStringencyFactor;
                DeconThrashParameters.MaxCharge = Parameters.MaxCharge;
                DeconThrashParameters.MaxFit = Parameters.MaxFit;
                DeconThrashParameters.MaxMW = Parameters.MaxMW;
                DeconThrashParameters.MinMZ = Parameters.MinMZ;
                DeconThrashParameters.MaxMZ = Parameters.MaxMZ;
                DeconThrashParameters.MaxScan = Parameters.MaxScan;
                DeconThrashParameters.MinIntensityForScore = Parameters.MinIntensityForScore;
                // hornParameters.MinS2N = ??     //TODO:  verify that this is no longer used
                DeconThrashParameters.NumPeaksForShoulder = Parameters.NumPeaksForShoulder;
                DeconThrashParameters.O16O18Media = Parameters.O16O18Media;
                DeconThrashParameters.PeptideMinBackgroundRatio = Parameters.PeptideMinBackgroundRatio;
                DeconThrashParameters.ProcessMSMS = Parameters.ProcessMSMS;
                DeconThrashParameters.RightFitStringencyFactor = Parameters.RightFitStringencyFactor;
                DeconThrashParameters.TagFormula = Parameters.TagFormula;
                DeconThrashParameters.ThrashOrNot = Parameters.ThrashOrNot;
                DeconThrashParameters.UseAbsolutePeptideIntensity = Parameters.UseAbsolutePeptideIntensity;
                DeconThrashParameters.UseMercuryCaching = Parameters.UseMercuryCaching;
                DeconThrashParameters.UseMZRange = Parameters.UseMZRange;
                DeconThrashParameters.NumPeaksUsedInAbundance = Parameters.NumPeaksUsedInAbundance;



                /* The following DeconEngine Horn parameters are used elsewhere in the new framework.  For
                 * example, Smoothing is now a Task that is performed after the MS is generated by the MSGenerator Task
                 * Smoothing-related parameters will be found within the task. 

                hornParameters.UseScanRange;
                hornParameters.MinScan;
                hornParameters.MaxScan;
                hornParameters.SGNumLeft;
                hornParameters.SGNumRight;
                hornParameters.SGOrder;
                hornParameters.SumSpectra;
                hornParameters.SumSpectraAcrossScanRange;
                hornParameters.UseSavitzkyGolaySmooth;
                hornParameters.ZeroFill;
                hornParameters.NumZerosToFill;
                hornParameters.ElementIsotopeComposition;
                */

                DeconThrashParameters.SumSpectraAcrossFrameRange = Parameters.SumSpectraAcrossFrameRange;
                DeconThrashParameters.SumSpectraAcrossScanRange = Parameters.SumSpectraAcrossScanRange;
                DeconThrashParameters.NumScansToSumOver = Parameters.NumScansToSumOver;
                DeconThrashParameters.NumScansToAdvance = Parameters.NumScansToAdvance;

                DeconThrashParameters.MaxScan = Parameters.MaxScan;

                DeconThrashParameters.SumSpectra = false;

                DeconThrashParameters.UseScanRange = false;
            }


            #region old code off
            //DeconToolsV2.HornTransform.clsHornTransformParameters hornParameters = new DeconToolsV2.HornTransform.clsHornTransformParameters();
            //hornParameters.AbsolutePeptideIntensity = 0.0;
            //hornParameters.AveragineFormula = "C4.9384 H7.7583 N1.3577 O1.4773 S0.0417";//SK
            //hornParameters.CCMass = 1.00727638;
            //hornParameters.CheckAllPatternsAgainstCharge1 = false;
            //hornParameters.CompleteFit = false;
            //hornParameters.DeleteIntensityThreshold = 10.0;
            //hornParameters.IsActualMonoMZUsed = false;
            //hornParameters.IsotopeFitType = DeconToolsV2.enmIsotopeFitType.AREA;
            //hornParameters.LeftFitStringencyFactor = 1.0;
            //hornParameters.MaxCharge = 10;
            //hornParameters.MaxFit = 0.25;
            //hornParameters.MaxMW = 10000.0;
            //hornParameters.MinMZ = 400;
            //hornParameters.MaxMZ = 2000;
            //hornParameters.MinIntensityForScore = 10;
            //// hornParameters.MinS2N = ??     //TODO:  verify that this is no longer used
            //hornParameters.NumPeaksForShoulder = 1;
            //hornParameters.O16O18Media = false;
            //hornParameters.PeptideMinBackgroundRatio = 5.0;
            //hornParameters.ProcessMSMS = false;
            //hornParameters.RightFitStringencyFactor = 1.0;
            //hornParameters.TagFormula = "";
            //hornParameters.ThrashOrNot = true;
            //hornParameters.UseAbsolutePeptideIntensity = false;
            //hornParameters.UseMercuryCaching = true;
            //hornParameters.UseMZRange = true;
            //hornParameters.NumPeaksUsedInAbundance = 1;

            ///* The following DeconEngine Horn parameters are used elsewhere in the new framework.  For
            // * example, Smoothing is now a Task that is performed after the MS is generated by the MSGenerator Task
            // * Smoothing-related parameters will be found within the task. 
             
            //hornParameters.UseScanRange;
            //hornParameters.MinScan;
            //hornParameters.MaxScan;
            //hornParameters.SGNumLeft;
            //hornParameters.SGNumRight;
            //hornParameters.SGOrder;
            //hornParameters.SumSpectra;
            //hornParameters.SumSpectraAcrossScanRange;
            //hornParameters.UseSavitzkyGolaySmooth;
            //hornParameters.ZeroFill;
            //hornParameters.NumZerosToFill;
            //hornParameters.ElementIsotopeComposition;
            //*/

            //hornParameters.MaxScan = 2147483647;
            #endregion
            return DeconThrashParameters;
        }

       
    }
}
